#include <sys/wait.h>
#include <unistd.h>
#include <errno.h>
#include <stdlib.h>//so we can use exit()
#include "utils.h"

int main(int argc, char *argv[]) {

    if(argc < 4) 
    {
        printf("Less number of arguments.\n");
        printf("./mapreduce #mappers #reducers inputFile\n");
        exit(0);
    }

    // ###### DO NOT REMOVE ######
    int nMappers 	= strtol(argv[1], NULL, 10);
    int nReducers 	= strtol(argv[2], NULL, 10);
    char *inputFile = argv[3];

    if(nMappers <= 1 || nReducers <= 0)
    {
        printf("Invalid number of mapper and reducers\n");
        exit(PROCESS_ERROR);
    }

    // ###### DO NOT REMOVE ######
    bookeepingCode();

    // ###### DO NOT REMOVE ######
    pid_t pid = fork();
    if(pid == 0)
    {
        //send chunks of data to the mappers in RR fashion
        sendChunkData(inputFile, nMappers);
        exit(0);
    }
    else if(pid < 0)
    {
        printf("Error sending chunk data\n");
        exit(PROCESS_ERROR);
    }
    sleep(1);


    // To do
    // spawn mappers processes and run 'mapper' executable using exec
    for (int i = 1; i <= nMappers; i += 1)
    {
        
        // Start spanwing
        pid = fork();

        if (pid < 0) 
        {
            // Error happened
            perror("Failed to fork");
            exit(PROCESS_ERROR);
        } 
        else if (pid == 0)
        {
            // This is child process
            char buf[100];          // "supposed to be 11 --> 10 digits + 1 digit for null termination"
            // Convert the i to string to send through the command line
            sprintf(buf, "%d", i);
            // Set up parameters
            char *args[] = {"mapper", buf, NULL};
            // Run the mapper with given parameters
            execv(*args, args);
            // If execv failed, this will be run
            printf("Error running execv to execute mapper\n");
            exit(PROCESS_ERROR);
        }
    }

    // To do
    // wait for all children to complete execution
    // Wait for mapper to end
    int status;
    pid_t childPID;
    while ((childPID = wait(&status)) != -1) 
    {
        if (status == PROCESS_ERROR) 
        {
            printf("Mapper with process id %d encountered error\n", childPID);
        }
    }


    // ###### DO NOT REMOVE ######
    // shuffle sends the word.txt files generated by mapper
    // to reducer based on a hash function
    pid = fork();
    if(pid == 0)
    {
        shuffle(nMappers, nReducers);
        exit(0);
    }
    else if(pid < 0)
    {
        printf("Error running shuffle\n");
        exit(PROCESS_ERROR);
    }
    sleep(1);


    // To do
    // spawn reducer processes and run 'reducer' executable using exec
    for (int i = 1; i <= nReducers; i += 1) 
    {
        pid = fork();

        if (pid < 0) 
        {
            perror("Failed to fork");
            exit(PROCESS_ERROR);
        } 
        else if (pid == 0)  // if it's the child
        {
            char buf[100];//"supposed to be 11 --> 10 digits + 1 digit for null termination"
            sprintf(buf, "%d", i);//send the i to a "string"
            char *args[] = {"reducer", buf, NULL};//might need const
            execv(*args, args);
            // If execv failed, this will be run
            printf("Error running execv to execute reducer\n");
            exit(PROCESS_ERROR);
        }

    }

    // To do
    // wait for all children to complete execution
    while ((childPID = wait(&status)) != -1) 
    {
        if (status == PROCESS_ERROR) 
        {
            printf("Reducer with process id %d encountered error\n", childPID);
        }
    }

    return 0;
}


